#!/bin/bash

#
# Bring the services up
#
function startNetwork {
  docker start ethbn eth1 eth2 eth3
  sleep 5
  echo "Start: starting network..."
  bootnodeIp=`docker inspect ethbn -f "{{.NetworkSettings.Networks.ethnet.IPAddress}}"`
  echo "Start: starting bootnode..."
  docker exec -u ethuser -d ethbn bash config/bootnode.sh $bootnodeIp
  sleep 10
  echo "Start: starting eth1, eth2, eth3..."
  docker exec -u ethuser -d eth1 bash config/node.sh start
  docker exec -u ethuser -d eth2 bash config/node.sh start
  docker exec -u ethuser -d eth3 bash config/node.sh start
  echo "Start: starting netstat node..."
  docker run -dP --network ethnet --name netstat -it -h netstat netstat-img
}

function show_info {
  netstatIp=`docker inspect netstat -f "{{.NetworkSettings.Networks.ethnet.IPAddress}}"`
  echo "Nestat: http://$netstatIp:3000"
}

if [[ $1 = "start" ]]; then
  startNetwork
  exit
fi

if [[ $1 = "stop" ]]; then
  echo "Stop: stopping node processes..."
  docker exec -u ethuser -d ethbn bash config/node.sh stop
  docker exec -u ethuser -d eth1  bash config/node.sh stop
  docker exec -u ethuser -d eth2  bash config/node.sh stop
  docker exec -u ethuser -d eth3  bash config/node.sh stop
  echo "Stop: stopping node instances..."
  docker stop ethbn eth1 eth2 eth3 netstat
  exit
fi

if [[ $1 = "deploy" ]]; then
  docker rm -f `docker ps -aq` # delete old containers
  docker network rm ethnet
  docker network create --driver bridge ethnet # create custom network

  # 3 nodes
  echo ">> Deploy:: creating node instances ..."
  docker run -dP --network ethnet --name ethbn -h ethbn -it ethimg
  docker run -dP --network ethnet --name eth1 -it -h eth1 ethimg
  docker run -dP --network ethnet --name eth2 -it -h eth2 ethimg
  docker run -dP --network ethnet --name eth3 -it -h eth3 ethimg

  # Prepare bootnode
  echo ">> Deploy: preparing bootnode ..."
  docker exec -u ethuser -d ethbn bash config/genKey.sh
  echo ">> Depoy: init eth nodes..."
  docker exec -u ethuser -d ethbn bash config/node.sh init
  docker exec -u ethuser -d eth1 bash config/node.sh init
  docker exec -u ethuser -d eth2 bash config/node.sh init
  docker exec -u ethuser -d eth3 bash config/node.sh init
  startNetwork
  exit
fi

if [[ $1 = "info" ]]; then
  show_info
  exit
fi

if [[ $1 = "login" ]]; then
  docker exec -it $2 bash
  exit
fi

if [[ $1 = "geth" ]]; then
  docker exec -it $2 geth attach data/geth.ipc console
  exit
fi

echo "Usage: cluster deploy|start|stop"
echo "                 deploy - create a new Ethereum network"
echo "                 start  - start the existing containers"
echo "                 stop   - stop the running containers" 
echo "       cluster login eth1|eth2|eth3|ethbn|netstat - opens a console" 
echo "       cluster geth eth1|eth2|eth3|ethbn|netstat - open geth console"
